@extends('layouts.app')

@section('title', 'Organizational Strategy')

@section('content')
<div class="container my-5">
    <div class="row">
        <div class="col">
            <p>Billions of dollars are spent in Afghanistan; donors are putting a lot of efforts and money without scrutinizing project implementations and disseminating results to public and wider development community. Afghanistan lacks a government wide Monitoring and Evaluation policy, there is also inconsistency in monitoring and evaluation practices across different government ministries. Donor projects that are implemented off budget implements monitoring and evaluation standards to a higher degree, while this is then decreased when referred to the on-budget projects of donors.</p>
            <p>Lack of streamlined evaluations across government entities is one of the biggest challenge that need to be addressed, there is lesser degree of trust on government from the donor agencies due to the fact that government is unable to justify donor funding and ensure accountability and transparency. Results of successful projects are rarely disseminated to wider development community and the public, lessons learned are not documented to take them forward in the future projects for improvements.</p>
            <p>2015 is a year of global transformation, in which the new Sustainable Development Goals were framed, and endorsed by the UN on 26th September. Social equity and gender equality are central to ensure the realization of sustainable and equitable development. Evaluation must be equipped to inform its design and implementation, both at global and national level. National development policies and programs should therefore be informed by evidence generated by credible national evaluation systems that are equity-focused and gender-responsive, while ensuring policy coherence at regional and global level.</p>
        </div>
        <div class="col">
            <p>EvalPartners, the global movement to strengthen national evaluation capacities for equity-focused and gender-responsive evaluation systems, co-led by International Organization for Cooperation in Evaluation (IOCE) and UN Women, declared 2015 as the International year of Evaluation. Several key stakeholders, including the United Nations Evaluation Group and the OECD/DAC EvalNet, joined the movement.</p>
            <p>Least Developed Countries (LDCs) such as Afghanistan are incapable to develop and implement coherent evaluation policies stand-alone, due to the fact that there are many other challenges and priorities for the government to tackle, therefore; evaluation societies and communities of practices should work side by side with the government, in collaboration with donor agencies and other CSOs to raise awareness for the importance of evaluation, increase demand for use and practice, and then gradually develop and implement evaluation standards.</p>
            <p>It is also very important that each and every step in promoting evaluation has a credible place for itself, and that buy-in for strengthening evaluation is obtained from the government, this is for the sake to successful implementation of the strategy to strengthen evaluation. Government is considered as a first and foremost stakeholder to promote the SDG and Evaluations agenda, and AfES intends to complement this role with the support from donor community and CSOs. AfES is also committed to coordinate efforts that aim to strengthen evaluations in Afghanistan and in the region; this is only possible with technical and financial support from the prospective donors in Afghanistan.</p>
        </div>
    </div>

    <div class="m-5">
        <h3 class="display-5 text-center">Approaches and Entry Points</h3>
        <p class="lead">It is imperative to identify successful approaches and entry points for taking forward and implementing any strategy. Therefore, AfES has carefully identified and intends to implement this strategy with the following approaches and entry points.</p>
    </div>

    <table class="table table-borderless">
        <thead>
            <tr>
                <th scope="col">ENTRY POINT</th>
                <th scope="col">APPROACH</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Capacity building of CSOs on Monitoring, Evaluation and Research</th>
                <td>AfES will reach out to potential CSOs to train them on Monitoring, Evaluation and Research. These trainings will be in the form of on-the-job training to build the human capacity of CSOs in evaluations so that they will contribute to the achievement of Sustainable Development in Afghanistan by having an oversight role on the government and donors.</td>
            </tr>
            <tr>
                <th scope="row">Institutionalization of Monitoring and Evaluation</th>
                <td>It is very important to institutionalize Monitoring and Evaluation, AfES intends to institutionalize M&E through working with government, donors and CSOs in order to develop, and subsequently implement coherent monitoring and evaluation policies and systems.</td>
            </tr>
            <tr>
                <th scope="row">Promoting Evaluation as a profession</th>
                <td>AfES will work with universities and educational institutions in Afghanistan and the region to encourage youth and emerging evaluators in order to enter the field of evaluation, and make their careers paths in the field of Evaluation. Moreover, AfES will also provide capacity building training to Youth and Emerging Evaluators (YEEs).</td>
            </tr>
            <tr>
                <th scope="row">Research</th>
                <td>Research provides insights and evidence for policy making and evidence-based decision making. AfES will focus on research as one of its main components in order to create bases of evidence for sustainable development and policy making in Afghanistan.</td>
            </tr>
            <tr>
                <th scope="row">Networking and Establishment of M&E Forums</th>
                <td>AfES intends to establish networking among evaluators, universities and educational institutions in order to create demand for use and practice of evaluation, and share knowledge and best practices across different stakeholders, this will also create an enabling environment for use of evaluation data.</td>
            </tr>
            <tr>
                <th scope="row">Identification of policy interventions</th>
                <td>AfES should work with partners, stakeholders, government institutions and CSOs to promote the global evaluation agenda, and the sustainable development goals in order to ensure that appetite for embedding evaluation in the development agenda is strengthened and the culture of evaluation is cultivated among development agencies and the government.</td>
            </tr>
            <tr>
                <th scope="row">Promoting the agenda of SDGs and Global Evaluation Agenda</th>
                <td>AfES should work with partners, stakeholders, government institutions and CSOs to promote the global evaluation agenda, and the sustainable development goals in order to ensure that appetite for embedding evaluation in the development agenda is strengthened and the culture of evaluation is cultivated among development agencies and the government.</td>
            </tr>
            <tr>
                <th scope="row">Awareness Raising</th>
                <td>AfES will also develop and implement awareness rising on Sustainable Development Goals, Evaluation and the principles for evaluations. This will enhance enabling environment and create a space for increased use and practice of evaluation in general.</td>
            </tr>
            <tr>
                <th scope="row">Publications</th>
                <td>AfES will also work on publications of newsletters, and other products that are related to evaluations. These will include study reports, evaluation reports and publications of specific evaluations that will be conducted by AfES.</td>
            </tr>
            <tr>
                <th scope="row">Regional Cooperation</th>
                <td>It is understood that there have already been enough progress in standardizing evaluation; therefore, it is vital to learn from others in the region. AfES will work with regional evaluation societies for sharing lessons learned and learning from others, activities will include joint conferences in Afghanistan, South Asia and Central Asia. Study tours and joined projects will also be implemented to strengthen and enhance regional cooperation</td>
            </tr>
            <tr>
                <th scope="row">Institutional Development of AfES</th>
                <td>AfES is a newly established evaluation society, one of the major objectives will remain to further develop AfES in terms of institutional development, and these will include development of policies, by-laws and charters for AfES.</td>
            </tr>
            <tr>
                <th scope="row">Localizing and Streamlining Evaluation in Afghanistan</th>
                <td>Major materials and methodologies in English are primarily available in English Language, it is very important to make them available in local languages, as well as modify them according to the needs and cultures, as well as adopt them based on situations. AfES will work to provide materials and methodologies in evaluation in local languages of Pashto and Dari. Moreover, those approaches that need to be adopted and modified will be streamlined in collaboration with the government, CSOs and development agencies in Afghanistan.</td>
            </tr>
        </tbody>
    </table>

    <div class="m-5">
        <h3 class="display-5 text-center">Potential Stakeholders and Sponsors</h3>
        <p class="lead">We at AfES understand that we cannot be successful without significant technical and financial assistance from government, members, CSOs, development agencies and donors. Therefore, we have identified potential stakeholders and sponsors in order to implement our strategy. These are identified as following:</p>
    </div>
</div>
@endsection
